[tools]
1password-cli = "latest"
aws = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
jq = "latest"
neovim = "latest"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
